#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mobet.Droid.Components.AmazingRefresharp.Resource", IsApplication=false)]

namespace Mobet.Droid.Components.AmazingRefresharp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int contentViewId = 2130771969;
			
			// aapt resource value: 0x7f01000c
			public static int fastScrollThumbWidth = 2130771980;
			
			// aapt resource value: 0x7f01000a
			public static int headerIconDrawable = 2130771978;
			
			// aapt resource value: 0x7f010000
			public static int headerId = 2130771968;
			
			// aapt resource value: 0x7f010009
			public static int headerTextColor = 2130771977;
			
			// aapt resource value: 0x7f010008
			public static int ptrHeaderBackground = 2130771976;
			
			// aapt resource value: 0x7f010002
			public static int pullDownProgressIndicatorId = 2130771970;
			
			// aapt resource value: 0x7f010004
			public static int pullDownTension = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public static int pullEnabled = 2130771979;
			
			// aapt resource value: 0x7f010005
			public static int pullToRefreshText = 2130771973;
			
			// aapt resource value: 0x7f010007
			public static int refreshingText = 2130771975;
			
			// aapt resource value: 0x7f010006
			public static int releaseToRefreshText = 2130771974;
			
			// aapt resource value: 0x7f010003
			public static int snapbackDuration = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public static int ptrsharp_sb_gradient_end = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int ptrsharp_sb_gradient_start = 2130968576;
			
			// aapt resource value: 0x7f040002
			public static int ptrsharp_sb_header_text = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int ptrsharp_sb_header_text_shadow = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public static int fastscroll_thumb_width = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int progress_medium_holo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int ptrsharp_serious_business_gradient = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int serious_business_arrow = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int serious_business_arrow2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int spinner_20_inner_holo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int spinner_20_outer_holo = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public static int header = 2131230721;
			
			// aapt resource value: 0x7f080000
			public static int header_container = 2131230720;
			
			// aapt resource value: 0x7f080003
			public static int icon = 2131230723;
			
			// aapt resource value: 0x7f080002
			public static int pullDownProgressIndicator = 2131230722;
			
			// aapt resource value: 0x7f080004
			public static int text = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int ptrsharp_header = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public static int library_name = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int ptrsharp_pull_to_refresh = 2131099649;
			
			// aapt resource value: 0x7f060003
			public static int ptrsharp_refreshing = 2131099651;
			
			// aapt resource value: 0x7f060002
			public static int ptrsharp_release_to_refresh = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public static int HoloProgressMedium = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AmazingRefreshsharpWrapper = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 1
			public static int AmazingRefreshsharpWrapper_contentViewId = 1;
			
			// aapt resource value: 12
			public static int AmazingRefreshsharpWrapper_fastScrollThumbWidth = 12;
			
			// aapt resource value: 10
			public static int AmazingRefreshsharpWrapper_headerIconDrawable = 10;
			
			// aapt resource value: 0
			public static int AmazingRefreshsharpWrapper_headerId = 0;
			
			// aapt resource value: 9
			public static int AmazingRefreshsharpWrapper_headerTextColor = 9;
			
			// aapt resource value: 8
			public static int AmazingRefreshsharpWrapper_ptrHeaderBackground = 8;
			
			// aapt resource value: 2
			public static int AmazingRefreshsharpWrapper_pullDownProgressIndicatorId = 2;
			
			// aapt resource value: 4
			public static int AmazingRefreshsharpWrapper_pullDownTension = 4;
			
			// aapt resource value: 11
			public static int AmazingRefreshsharpWrapper_pullEnabled = 11;
			
			// aapt resource value: 5
			public static int AmazingRefreshsharpWrapper_pullToRefreshText = 5;
			
			// aapt resource value: 7
			public static int AmazingRefreshsharpWrapper_refreshingText = 7;
			
			// aapt resource value: 6
			public static int AmazingRefreshsharpWrapper_releaseToRefreshText = 6;
			
			// aapt resource value: 3
			public static int AmazingRefreshsharpWrapper_snapbackDuration = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
