#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mobet.Droid.Components.ResideMenu.Resource", IsApplication=false)]

namespace Mobet.Droid.Components.ResideMenu
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public static int behind_offset = 2130771971;
			
			// aapt resource value: 0x7f010005
			public static int behind_scroll_scale = 2130771973;
			
			// aapt resource value: 0x7f010004
			public static int behind_width = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public static int fade_degree = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public static int fade_enabled = 2130771978;
			
			// aapt resource value: 0x7f010000
			public static int mode = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public static int selector_drawable = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public static int selector_enabled = 2130771980;
			
			// aapt resource value: 0x7f010008
			public static int shadow_drawable = 2130771976;
			
			// aapt resource value: 0x7f010009
			public static int shadow_width = 2130771977;
			
			// aapt resource value: 0x7f010006
			public static int touch_mode_above = 2130771974;
			
			// aapt resource value: 0x7f010007
			public static int touch_mode_behind = 2130771975;
			
			// aapt resource value: 0x7f010001
			public static int view_above = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int view_behind = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030003
			public static int fullscreen = 2130903043;
			
			// aapt resource value: 0x7f030001
			public static int left = 2130903041;
			
			// aapt resource value: 0x7f030004
			public static int margin = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int reside_menu_main = 2130903045;
			
			// aapt resource value: 0x7f030002
			public static int right = 2130903042;
			
			// aapt resource value: 0x7f030000
			public static int selected_view = 2130903040;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int reside_menu_main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] reside_menu = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 3
			public static int reside_menu_behind_offset = 3;
			
			// aapt resource value: 5
			public static int reside_menu_behind_scroll_scale = 5;
			
			// aapt resource value: 4
			public static int reside_menu_behind_width = 4;
			
			// aapt resource value: 11
			public static int reside_menu_fade_degree = 11;
			
			// aapt resource value: 10
			public static int reside_menu_fade_enabled = 10;
			
			// aapt resource value: 0
			public static int reside_menu_mode = 0;
			
			// aapt resource value: 13
			public static int reside_menu_selector_drawable = 13;
			
			// aapt resource value: 12
			public static int reside_menu_selector_enabled = 12;
			
			// aapt resource value: 8
			public static int reside_menu_shadow_drawable = 8;
			
			// aapt resource value: 9
			public static int reside_menu_shadow_width = 9;
			
			// aapt resource value: 6
			public static int reside_menu_touch_mode_above = 6;
			
			// aapt resource value: 7
			public static int reside_menu_touch_mode_behind = 7;
			
			// aapt resource value: 1
			public static int reside_menu_view_above = 1;
			
			// aapt resource value: 2
			public static int reside_menu_view_behind = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
