#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mobet.Metting.Droid.Resource", IsApplication=true)]

namespace Mobet.Metting.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Attribute.contentViewId = global::Mobet.Metting.Droid.Resource.Attribute.contentViewId;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Attribute.fastScrollThumbWidth = global::Mobet.Metting.Droid.Resource.Attribute.fastScrollThumbWidth;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Attribute.headerIconDrawable = global::Mobet.Metting.Droid.Resource.Attribute.headerIconDrawable;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Attribute.headerId = global::Mobet.Metting.Droid.Resource.Attribute.headerId;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Attribute.headerTextColor = global::Mobet.Metting.Droid.Resource.Attribute.headerTextColor;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Attribute.ptrHeaderBackground = global::Mobet.Metting.Droid.Resource.Attribute.ptrHeaderBackground;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Attribute.pullDownProgressIndicatorId = global::Mobet.Metting.Droid.Resource.Attribute.pullDownProgressIndicatorId;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Attribute.pullDownTension = global::Mobet.Metting.Droid.Resource.Attribute.pullDownTension;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Attribute.pullEnabled = global::Mobet.Metting.Droid.Resource.Attribute.pullEnabled;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Attribute.pullToRefreshText = global::Mobet.Metting.Droid.Resource.Attribute.pullToRefreshText;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Attribute.refreshingText = global::Mobet.Metting.Droid.Resource.Attribute.refreshingText;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Attribute.releaseToRefreshText = global::Mobet.Metting.Droid.Resource.Attribute.releaseToRefreshText;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Attribute.snapbackDuration = global::Mobet.Metting.Droid.Resource.Attribute.snapbackDuration;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Color.ptrsharp_sb_gradient_end = global::Mobet.Metting.Droid.Resource.Color.ptrsharp_sb_gradient_end;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Color.ptrsharp_sb_gradient_start = global::Mobet.Metting.Droid.Resource.Color.ptrsharp_sb_gradient_start;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Color.ptrsharp_sb_header_text = global::Mobet.Metting.Droid.Resource.Color.ptrsharp_sb_header_text;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Color.ptrsharp_sb_header_text_shadow = global::Mobet.Metting.Droid.Resource.Color.ptrsharp_sb_header_text_shadow;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Dimension.fastscroll_thumb_width = global::Mobet.Metting.Droid.Resource.Dimension.fastscroll_thumb_width;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Drawable.progress_medium_holo = global::Mobet.Metting.Droid.Resource.Drawable.progress_medium_holo;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Drawable.ptrsharp_serious_business_gradient = global::Mobet.Metting.Droid.Resource.Drawable.ptrsharp_serious_business_gradient;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Drawable.serious_business_arrow = global::Mobet.Metting.Droid.Resource.Drawable.serious_business_arrow;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Drawable.serious_business_arrow2 = global::Mobet.Metting.Droid.Resource.Drawable.serious_business_arrow2;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Drawable.serious_business_arrow_up = global::Mobet.Metting.Droid.Resource.Drawable.serious_business_arrow_up;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Drawable.spinner_20_inner_holo = global::Mobet.Metting.Droid.Resource.Drawable.spinner_20_inner_holo;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Drawable.spinner_20_outer_holo = global::Mobet.Metting.Droid.Resource.Drawable.spinner_20_outer_holo;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Id.header = global::Mobet.Metting.Droid.Resource.Id.header;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Id.header_container = global::Mobet.Metting.Droid.Resource.Id.header_container;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Id.icon = global::Mobet.Metting.Droid.Resource.Id.icon;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Id.pullDownProgressIndicator = global::Mobet.Metting.Droid.Resource.Id.pullDownProgressIndicator;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Id.text = global::Mobet.Metting.Droid.Resource.Id.text;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Layout.ptrsharp_header = global::Mobet.Metting.Droid.Resource.Layout.ptrsharp_header;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.String.library_name = global::Mobet.Metting.Droid.Resource.String.library_name;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.String.ptrsharp_pull_to_refresh = global::Mobet.Metting.Droid.Resource.String.ptrsharp_pull_to_refresh;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.String.ptrsharp_refreshing = global::Mobet.Metting.Droid.Resource.String.ptrsharp_refreshing;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.String.ptrsharp_release_to_refresh = global::Mobet.Metting.Droid.Resource.String.ptrsharp_release_to_refresh;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Style.HoloProgressMedium = global::Mobet.Metting.Droid.Resource.Style.HoloProgressMedium;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Styleable.AmazingRefreshsharpWrapper = global::Mobet.Metting.Droid.Resource.Styleable.AmazingRefreshsharpWrapper;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Styleable.AmazingRefreshsharpWrapper_contentViewId = global::Mobet.Metting.Droid.Resource.Styleable.AmazingRefreshsharpWrapper_contentViewId;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Styleable.AmazingRefreshsharpWrapper_fastScrollThumbWidth = global::Mobet.Metting.Droid.Resource.Styleable.AmazingRefreshsharpWrapper_fastScrollThumbWidth;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Styleable.AmazingRefreshsharpWrapper_headerIconDrawable = global::Mobet.Metting.Droid.Resource.Styleable.AmazingRefreshsharpWrapper_headerIconDrawable;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Styleable.AmazingRefreshsharpWrapper_headerId = global::Mobet.Metting.Droid.Resource.Styleable.AmazingRefreshsharpWrapper_headerId;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Styleable.AmazingRefreshsharpWrapper_headerTextColor = global::Mobet.Metting.Droid.Resource.Styleable.AmazingRefreshsharpWrapper_headerTextColor;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Styleable.AmazingRefreshsharpWrapper_ptrHeaderBackground = global::Mobet.Metting.Droid.Resource.Styleable.AmazingRefreshsharpWrapper_ptrHeaderBackground;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Styleable.AmazingRefreshsharpWrapper_pullDownProgressIndicatorId = global::Mobet.Metting.Droid.Resource.Styleable.AmazingRefreshsharpWrapper_pullDownProgressIndicatorId;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Styleable.AmazingRefreshsharpWrapper_pullDownTension = global::Mobet.Metting.Droid.Resource.Styleable.AmazingRefreshsharpWrapper_pullDownTension;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Styleable.AmazingRefreshsharpWrapper_pullEnabled = global::Mobet.Metting.Droid.Resource.Styleable.AmazingRefreshsharpWrapper_pullEnabled;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Styleable.AmazingRefreshsharpWrapper_pullToRefreshText = global::Mobet.Metting.Droid.Resource.Styleable.AmazingRefreshsharpWrapper_pullToRefreshText;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Styleable.AmazingRefreshsharpWrapper_refreshingText = global::Mobet.Metting.Droid.Resource.Styleable.AmazingRefreshsharpWrapper_refreshingText;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Styleable.AmazingRefreshsharpWrapper_releaseToRefreshText = global::Mobet.Metting.Droid.Resource.Styleable.AmazingRefreshsharpWrapper_releaseToRefreshText;
			global::Mobet.Droid.Components.AmazingRefresharp.Resource.Styleable.AmazingRefreshsharpWrapper_snapbackDuration = global::Mobet.Metting.Droid.Resource.Styleable.AmazingRefreshsharpWrapper_snapbackDuration;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.MvxBind = global::Mobet.Metting.Droid.Resource.Attribute.MvxBind;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.MvxDropDownItemTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.MvxGroupItemTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.MvxItemTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxItemTemplate;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.MvxLang = global::Mobet.Metting.Droid.Resource.Attribute.MvxLang;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.MvxSource = global::Mobet.Metting.Droid.Resource.Attribute.MvxSource;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.MvxTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxTemplate;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.behind_offset = global::Mobet.Metting.Droid.Resource.Attribute.behind_offset;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.behind_scroll_scale = global::Mobet.Metting.Droid.Resource.Attribute.behind_scroll_scale;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.behind_width = global::Mobet.Metting.Droid.Resource.Attribute.behind_width;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.fade_degree = global::Mobet.Metting.Droid.Resource.Attribute.fade_degree;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.fade_enabled = global::Mobet.Metting.Droid.Resource.Attribute.fade_enabled;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.mode = global::Mobet.Metting.Droid.Resource.Attribute.mode;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.selector_drawable = global::Mobet.Metting.Droid.Resource.Attribute.selector_drawable;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.selector_enabled = global::Mobet.Metting.Droid.Resource.Attribute.selector_enabled;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.shadow_drawable = global::Mobet.Metting.Droid.Resource.Attribute.shadow_drawable;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.shadow_width = global::Mobet.Metting.Droid.Resource.Attribute.shadow_width;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.touch_mode_above = global::Mobet.Metting.Droid.Resource.Attribute.touch_mode_above;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.touch_mode_behind = global::Mobet.Metting.Droid.Resource.Attribute.touch_mode_behind;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.view_above = global::Mobet.Metting.Droid.Resource.Attribute.view_above;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.view_behind = global::Mobet.Metting.Droid.Resource.Attribute.view_behind;
			global::Mobet.Droid.Components.ResideMenu.Resource.Id.MvvmCrossTagId = global::Mobet.Metting.Droid.Resource.Id.MvvmCrossTagId;
			global::Mobet.Droid.Components.ResideMenu.Resource.Id.MvxBindingTagUnique = global::Mobet.Metting.Droid.Resource.Id.MvxBindingTagUnique;
			global::Mobet.Droid.Components.ResideMenu.Resource.Id.fullscreen = global::Mobet.Metting.Droid.Resource.Id.fullscreen;
			global::Mobet.Droid.Components.ResideMenu.Resource.Id.left = global::Mobet.Metting.Droid.Resource.Id.left;
			global::Mobet.Droid.Components.ResideMenu.Resource.Id.margin = global::Mobet.Metting.Droid.Resource.Id.margin;
			global::Mobet.Droid.Components.ResideMenu.Resource.Id.reside_menu_main = global::Mobet.Metting.Droid.Resource.Id.reside_menu_main;
			global::Mobet.Droid.Components.ResideMenu.Resource.Id.right = global::Mobet.Metting.Droid.Resource.Id.right;
			global::Mobet.Droid.Components.ResideMenu.Resource.Id.selected_view = global::Mobet.Metting.Droid.Resource.Id.selected_view;
			global::Mobet.Droid.Components.ResideMenu.Resource.Layout.reside_menu_main = global::Mobet.Metting.Droid.Resource.Layout.reside_menu_main;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.MvxBinding = global::Mobet.Metting.Droid.Resource.Styleable.MvxBinding;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.MvxBinding_MvxBind = global::Mobet.Metting.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.MvxBinding_MvxLang = global::Mobet.Metting.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.MvxControl = global::Mobet.Metting.Droid.Resource.Styleable.MvxControl;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.MvxControl_MvxTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.MvxExpandableListView = global::Mobet.Metting.Droid.Resource.Styleable.MvxExpandableListView;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.MvxImageView = global::Mobet.Metting.Droid.Resource.Styleable.MvxImageView;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.MvxImageView_MvxSource = global::Mobet.Metting.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.MvxListView = global::Mobet.Metting.Droid.Resource.Styleable.MvxListView;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.MvxListView_MvxItemTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu = global::Mobet.Metting.Droid.Resource.Styleable.reside_menu;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_behind_offset = global::Mobet.Metting.Droid.Resource.Styleable.reside_menu_behind_offset;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_behind_scroll_scale = global::Mobet.Metting.Droid.Resource.Styleable.reside_menu_behind_scroll_scale;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_behind_width = global::Mobet.Metting.Droid.Resource.Styleable.reside_menu_behind_width;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_fade_degree = global::Mobet.Metting.Droid.Resource.Styleable.reside_menu_fade_degree;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_fade_enabled = global::Mobet.Metting.Droid.Resource.Styleable.reside_menu_fade_enabled;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_mode = global::Mobet.Metting.Droid.Resource.Styleable.reside_menu_mode;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_selector_drawable = global::Mobet.Metting.Droid.Resource.Styleable.reside_menu_selector_drawable;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_selector_enabled = global::Mobet.Metting.Droid.Resource.Styleable.reside_menu_selector_enabled;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_shadow_drawable = global::Mobet.Metting.Droid.Resource.Styleable.reside_menu_shadow_drawable;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_shadow_width = global::Mobet.Metting.Droid.Resource.Styleable.reside_menu_shadow_width;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_touch_mode_above = global::Mobet.Metting.Droid.Resource.Styleable.reside_menu_touch_mode_above;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_touch_mode_behind = global::Mobet.Metting.Droid.Resource.Styleable.reside_menu_touch_mode_behind;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_view_above = global::Mobet.Metting.Droid.Resource.Styleable.reside_menu_view_above;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_view_behind = global::Mobet.Metting.Droid.Resource.Styleable.reside_menu_view_behind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::Mobet.Metting.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::Mobet.Metting.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::Mobet.Metting.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::Mobet.Metting.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::Mobet.Metting.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::Mobet.Metting.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::Mobet.Metting.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::Mobet.Metting.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::Mobet.Metting.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::Mobet.Metting.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::Mobet.Metting.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::Mobet.Metting.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::Mobet.Metting.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxBind = global::Mobet.Metting.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxDropDownItemTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxGroupItemTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxItemTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxLang = global::Mobet.Metting.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxSource = global::Mobet.Metting.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Id.MvvmCrossTagId = global::Mobet.Metting.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Droid.FullFragging.Resource.Id.MvxBindingTagUnique = global::Mobet.Metting.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxBinding = global::Mobet.Metting.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxBinding_MvxBind = global::Mobet.Metting.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxBinding_MvxLang = global::Mobet.Metting.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxControl = global::Mobet.Metting.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxControl_MvxTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxExpandableListView = global::Mobet.Metting.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxImageView = global::Mobet.Metting.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxImageView_MvxSource = global::Mobet.Metting.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxListView = global::Mobet.Metting.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxListView_MvxItemTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int MvxBind = 2130771972;
			
			// aapt resource value: 0x7f010008
			public const int MvxDropDownItemTemplate = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int MvxGroupItemTemplate = 2130771977;
			
			// aapt resource value: 0x7f010007
			public const int MvxItemTemplate = 2130771975;
			
			// aapt resource value: 0x7f010005
			public const int MvxLang = 2130771973;
			
			// aapt resource value: 0x7f01000a
			public const int MvxSource = 2130771978;
			
			// aapt resource value: 0x7f010006
			public const int MvxTemplate = 2130771974;
			
			// aapt resource value: 0x7f01000e
			public const int behind_offset = 2130771982;
			
			// aapt resource value: 0x7f010010
			public const int behind_scroll_scale = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public const int behind_width = 2130771983;
			
			// aapt resource value: 0x7f010001
			public const int civ_border_color = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int civ_border_overlay = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int civ_border_width = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int civ_fill_color = 2130771971;
			
			// aapt resource value: 0x7f01001a
			public const int contentViewId = 2130771994;
			
			// aapt resource value: 0x7f010016
			public const int fade_degree = 2130771990;
			
			// aapt resource value: 0x7f010015
			public const int fade_enabled = 2130771989;
			
			// aapt resource value: 0x7f010025
			public const int fastScrollThumbWidth = 2130772005;
			
			// aapt resource value: 0x7f010023
			public const int headerIconDrawable = 2130772003;
			
			// aapt resource value: 0x7f010019
			public const int headerId = 2130771993;
			
			// aapt resource value: 0x7f010022
			public const int headerTextColor = 2130772002;
			
			// aapt resource value: 0x7f01000b
			public const int mode = 2130771979;
			
			// aapt resource value: 0x7f010021
			public const int ptrHeaderBackground = 2130772001;
			
			// aapt resource value: 0x7f01001b
			public const int pullDownProgressIndicatorId = 2130771995;
			
			// aapt resource value: 0x7f01001d
			public const int pullDownTension = 2130771997;
			
			// aapt resource value: 0x7f010024
			public const int pullEnabled = 2130772004;
			
			// aapt resource value: 0x7f01001e
			public const int pullToRefreshText = 2130771998;
			
			// aapt resource value: 0x7f010020
			public const int refreshingText = 2130772000;
			
			// aapt resource value: 0x7f01001f
			public const int releaseToRefreshText = 2130771999;
			
			// aapt resource value: 0x7f010018
			public const int selector_drawable = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int selector_enabled = 2130771991;
			
			// aapt resource value: 0x7f010013
			public const int shadow_drawable = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int shadow_width = 2130771988;
			
			// aapt resource value: 0x7f01001c
			public const int snapbackDuration = 2130771996;
			
			// aapt resource value: 0x7f010011
			public const int touch_mode_above = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int touch_mode_behind = 2130771986;
			
			// aapt resource value: 0x7f01000c
			public const int view_above = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int view_behind = 2130771981;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050004
			public const int content_background = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int ptrsharp_sb_gradient_end = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int ptrsharp_sb_gradient_start = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int ptrsharp_sb_header_text = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ptrsharp_sb_header_text_shadow = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int status_bar = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int fastscroll_thumb_width = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int list_padding = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int nav_width = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int reside_menu_offset = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int shadow_width = 2131099652;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_left = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Avatar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_empty_view_bg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_search_button = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int erg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int login_button = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int login_button_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int login_button_selector = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int login_input_bottom = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int login_input_top = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int menu_bg_blue = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int menu_bg_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int menu_bg_dark_deep = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int menu_bg_header = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int menu_bg_night = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int menu_bg_white = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int menu_icon_level = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int menu_icon_level_sun = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int menu_icon_qr_code = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int menu_icon_richstatus = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int menu_icon_setting = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int menu_icon_weather = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int progress_medium_holo = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ptrsharp_serious_business_gradient = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int reside_menu_shadow = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int rounded_rect = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int serious_business_arrow = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int serious_business_arrow2 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int serious_business_arrow_up = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int setting_layout_item = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int setting_layout_item_first = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int setting_layout_item_first_pressed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int setting_layout_item_first_selector = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int setting_layout_item_pressed = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int setting_layout_item_selector = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int skin_tab_icon_call_normal = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int skin_tab_icon_call_selected = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int skin_tab_icon_contact_normal = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int skin_tab_icon_contact_selected = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int skin_tab_icon_conversation_normal = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int skin_tab_icon_conversation_selected = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int skin_tab_icon_plugin_normal = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int skin_tab_icon_plugin_selected = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int spinner_20_inner_holo = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int spinner_20_outer_holo = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int splash = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int splash_1 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int splash_2 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int splash_3 = 2130837554;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int MvvmCrossTagId = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MvxBindingTagUnique = 2130968577;
			
			// aapt resource value: 0x7f04001f
			public const int button_splash_skip = 2130968607;
			
			// aapt resource value: 0x7f040005
			public const int fullscreen = 2130968581;
			
			// aapt resource value: 0x7f040018
			public const int header = 2130968600;
			
			// aapt resource value: 0x7f040017
			public const int header_container = 2130968599;
			
			// aapt resource value: 0x7f04001a
			public const int icon = 2130968602;
			
			// aapt resource value: 0x7f040003
			public const int left = 2130968579;
			
			// aapt resource value: 0x7f04000f
			public const int main_conversation_name = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int main_conversation_say = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int main_conversation_time = 2130968593;
			
			// aapt resource value: 0x7f04000d
			public const int main_frame_content = 2130968589;
			
			// aapt resource value: 0x7f040008
			public const int main_frame_footer = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int main_frame_footer_call = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int main_frame_footer_contact = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int main_frame_footer_conversation = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int main_frame_footer_plugin = 2130968588;
			
			// aapt resource value: 0x7f040007
			public const int main_frame_header = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int margin = 2130968582;
			
			// aapt resource value: 0x7f040012
			public const int menu_fragment_common = 2130968594;
			
			// aapt resource value: 0x7f040014
			public const int menu_frame_footer = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int menu_frame_header = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int menu_frame_personal_button_setting = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int menu_frame_personal_button_weather = 2130968598;
			
			// aapt resource value: 0x7f04000e
			public const int ptr_wrapper = 2130968590;
			
			// aapt resource value: 0x7f040019
			public const int pullDownProgressIndicator = 2130968601;
			
			// aapt resource value: 0x7f04001c
			public const int reside_menu_main = 2130968604;
			
			// aapt resource value: 0x7f040004
			public const int right = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int selected_view = 2130968578;
			
			// aapt resource value: 0x7f04001e
			public const int splash_viewgroup = 2130968606;
			
			// aapt resource value: 0x7f04001d
			public const int splash_viewpager = 2130968605;
			
			// aapt resource value: 0x7f04001b
			public const int text = 2130968603;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int num_cols = 2131296256;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int common_empty_view = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int main_frame_call = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int main_frame_contact = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int main_frame_conversation = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int main_frame_conversation_item = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int main_frame_plugin = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int main_search_bar = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int menu_frame_layout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int menu_frame_personal = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ptrsharp_header = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int reside_menu_main = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int setting = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int splash = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int library_name = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int ptrsharp_pull_to_refresh = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int ptrsharp_refreshing = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int ptrsharp_release_to_refresh = 2131165186;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int HoloProgressMedium = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int Theme_DeviceDefaultLightNoActionBar = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AmazingRefreshsharpWrapper = new int[] {
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005};
			
			// aapt resource value: 1
			public const int AmazingRefreshsharpWrapper_contentViewId = 1;
			
			// aapt resource value: 12
			public const int AmazingRefreshsharpWrapper_fastScrollThumbWidth = 12;
			
			// aapt resource value: 10
			public const int AmazingRefreshsharpWrapper_headerIconDrawable = 10;
			
			// aapt resource value: 0
			public const int AmazingRefreshsharpWrapper_headerId = 0;
			
			// aapt resource value: 9
			public const int AmazingRefreshsharpWrapper_headerTextColor = 9;
			
			// aapt resource value: 8
			public const int AmazingRefreshsharpWrapper_ptrHeaderBackground = 8;
			
			// aapt resource value: 2
			public const int AmazingRefreshsharpWrapper_pullDownProgressIndicatorId = 2;
			
			// aapt resource value: 4
			public const int AmazingRefreshsharpWrapper_pullDownTension = 4;
			
			// aapt resource value: 11
			public const int AmazingRefreshsharpWrapper_pullEnabled = 11;
			
			// aapt resource value: 5
			public const int AmazingRefreshsharpWrapper_pullToRefreshText = 5;
			
			// aapt resource value: 7
			public const int AmazingRefreshsharpWrapper_refreshingText = 7;
			
			// aapt resource value: 6
			public const int AmazingRefreshsharpWrapper_releaseToRefreshText = 6;
			
			// aapt resource value: 3
			public const int AmazingRefreshsharpWrapper_snapbackDuration = 3;
			
			public static int[] CircleImageView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int CircleImageView_civ_border_color = 1;
			
			// aapt resource value: 2
			public const int CircleImageView_civ_border_overlay = 2;
			
			// aapt resource value: 0
			public const int CircleImageView_civ_border_width = 0;
			
			// aapt resource value: 3
			public const int CircleImageView_civ_fill_color = 3;
			
			public static int[] MvxBinding = new int[] {
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771977};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771978};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] reside_menu = new int[] {
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992};
			
			// aapt resource value: 3
			public const int reside_menu_behind_offset = 3;
			
			// aapt resource value: 5
			public const int reside_menu_behind_scroll_scale = 5;
			
			// aapt resource value: 4
			public const int reside_menu_behind_width = 4;
			
			// aapt resource value: 11
			public const int reside_menu_fade_degree = 11;
			
			// aapt resource value: 10
			public const int reside_menu_fade_enabled = 10;
			
			// aapt resource value: 0
			public const int reside_menu_mode = 0;
			
			// aapt resource value: 13
			public const int reside_menu_selector_drawable = 13;
			
			// aapt resource value: 12
			public const int reside_menu_selector_enabled = 12;
			
			// aapt resource value: 8
			public const int reside_menu_shadow_drawable = 8;
			
			// aapt resource value: 9
			public const int reside_menu_shadow_width = 9;
			
			// aapt resource value: 6
			public const int reside_menu_touch_mode_above = 6;
			
			// aapt resource value: 7
			public const int reside_menu_touch_mode_behind = 7;
			
			// aapt resource value: 1
			public const int reside_menu_view_above = 1;
			
			// aapt resource value: 2
			public const int reside_menu_view_behind = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
