#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mobet.Metting.Droid.Resource", IsApplication=true)]

namespace Mobet.Metting.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::Mobet.Metting.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::Mobet.Metting.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::Mobet.Metting.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::Mobet.Metting.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::Mobet.Metting.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::Mobet.Metting.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::Mobet.Metting.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::Mobet.Metting.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::Mobet.Metting.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::Mobet.Metting.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::Mobet.Metting.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::Mobet.Metting.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::Mobet.Metting.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxBind = global::Mobet.Metting.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxDropDownItemTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxGroupItemTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxItemTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxLang = global::Mobet.Metting.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxSource = global::Mobet.Metting.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxTemplate = global::Mobet.Metting.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Id.MvvmCrossTagId = global::Mobet.Metting.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Droid.FullFragging.Resource.Id.MvxBindingTagUnique = global::Mobet.Metting.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxBinding = global::Mobet.Metting.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxBinding_MvxBind = global::Mobet.Metting.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxBinding_MvxLang = global::Mobet.Metting.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxControl = global::Mobet.Metting.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxControl_MvxTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxExpandableListView = global::Mobet.Metting.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxImageView = global::Mobet.Metting.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxImageView_MvxSource = global::Mobet.Metting.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxListView = global::Mobet.Metting.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxListView_MvxItemTemplate = global::Mobet.Metting.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int MvxBind = 2130771972;
			
			// aapt resource value: 0x7f010008
			public const int MvxDropDownItemTemplate = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int MvxGroupItemTemplate = 2130771977;
			
			// aapt resource value: 0x7f010007
			public const int MvxItemTemplate = 2130771975;
			
			// aapt resource value: 0x7f010005
			public const int MvxLang = 2130771973;
			
			// aapt resource value: 0x7f01000a
			public const int MvxSource = 2130771978;
			
			// aapt resource value: 0x7f010006
			public const int MvxTemplate = 2130771974;
			
			// aapt resource value: 0x7f010001
			public const int civ_border_color = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int civ_border_overlay = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int civ_border_width = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int civ_fill_color = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_left = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Avatar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int login_button = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int login_button_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int login_button_selector = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int login_input_bottom = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int login_input_top = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int setting_layout_item = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int setting_layout_item_first = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int setting_layout_item_first_pressed = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int setting_layout_item_first_selector = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int setting_layout_item_pressed = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int setting_layout_item_selector = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int splash = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int MvvmCrossTagId = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MvxBindingTagUnique = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int MyButton = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int button1 = 2130968578;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Setting = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Login = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_DeviceDefaultLightNoActionBar = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleImageView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int CircleImageView_civ_border_color = 1;
			
			// aapt resource value: 2
			public const int CircleImageView_civ_border_overlay = 2;
			
			// aapt resource value: 0
			public const int CircleImageView_civ_border_width = 0;
			
			// aapt resource value: 3
			public const int CircleImageView_civ_fill_color = 3;
			
			public static int[] MvxBinding = new int[] {
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771977};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771978};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
