#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mobet.Droid.Components.ResideMenu.Sample.Resource", IsApplication=true)]

namespace Mobet.Droid.Components.ResideMenu.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.behind_offset = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Attribute.behind_offset;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.behind_scroll_scale = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Attribute.behind_scroll_scale;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.behind_width = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Attribute.behind_width;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.fade_degree = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Attribute.fade_degree;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.fade_enabled = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Attribute.fade_enabled;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.mode = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Attribute.mode;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.selector_drawable = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Attribute.selector_drawable;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.selector_enabled = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Attribute.selector_enabled;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.shadow_drawable = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Attribute.shadow_drawable;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.shadow_width = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Attribute.shadow_width;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.touch_mode_above = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Attribute.touch_mode_above;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.touch_mode_behind = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Attribute.touch_mode_behind;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.view_above = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Attribute.view_above;
			global::Mobet.Droid.Components.ResideMenu.Resource.Attribute.view_behind = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Attribute.view_behind;
			global::Mobet.Droid.Components.ResideMenu.Resource.Id.fullscreen = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Id.fullscreen;
			global::Mobet.Droid.Components.ResideMenu.Resource.Id.left = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Id.left;
			global::Mobet.Droid.Components.ResideMenu.Resource.Id.margin = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Id.margin;
			global::Mobet.Droid.Components.ResideMenu.Resource.Id.reside_menu_main = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Id.reside_menu_main;
			global::Mobet.Droid.Components.ResideMenu.Resource.Id.right = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Id.right;
			global::Mobet.Droid.Components.ResideMenu.Resource.Id.selected_view = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Id.selected_view;
			global::Mobet.Droid.Components.ResideMenu.Resource.Layout.reside_menu_main = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Layout.reside_menu_main;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Styleable.reside_menu;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_behind_offset = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Styleable.reside_menu_behind_offset;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_behind_scroll_scale = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Styleable.reside_menu_behind_scroll_scale;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_behind_width = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Styleable.reside_menu_behind_width;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_fade_degree = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Styleable.reside_menu_fade_degree;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_fade_enabled = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Styleable.reside_menu_fade_enabled;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_mode = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Styleable.reside_menu_mode;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_selector_drawable = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Styleable.reside_menu_selector_drawable;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_selector_enabled = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Styleable.reside_menu_selector_enabled;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_shadow_drawable = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Styleable.reside_menu_shadow_drawable;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_shadow_width = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Styleable.reside_menu_shadow_width;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_touch_mode_above = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Styleable.reside_menu_touch_mode_above;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_touch_mode_behind = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Styleable.reside_menu_touch_mode_behind;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_view_above = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Styleable.reside_menu_view_above;
			global::Mobet.Droid.Components.ResideMenu.Resource.Styleable.reside_menu_view_behind = global::Mobet.Droid.Components.ResideMenu.Sample.Resource.Styleable.reside_menu_view_behind;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int birds = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int birds_img = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int color_names = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int behind_offset = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int behind_scroll_scale = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int behind_width = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int fade_degree = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int fade_enabled = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int mode = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public const int selector_drawable = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int selector_enabled = 2130771980;
			
			// aapt resource value: 0x7f010008
			public const int shadow_drawable = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int shadow_width = 2130771977;
			
			// aapt resource value: 0x7f010006
			public const int touch_mode_above = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int touch_mode_behind = 2130771975;
			
			// aapt resource value: 0x7f010001
			public const int view_above = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int view_behind = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060004
			public const int black = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int blue = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int green = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int red = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int white = 2131099651;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070001
			public const int list_padding = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int residemenu_offset = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int shadow_width = 2131165186;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int eagle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int flamingo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int heron = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_github = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int indicator = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int new_indicator = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int octocat = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int octocat_scaled = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ostrich = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int peacock = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int penguin = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int shadow = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int shadowright = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int toucan = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int turkey = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int vulture = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040005
			public const int content_common_fragment = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int fullscreen = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int left = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int main_btn_changing_fragments = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int margin = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int menu_fragment_common = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int reside_menu_main = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int right = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int selected_view = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int num_cols = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int content_frame_common = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int menu_frame_color = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int menu_frame_common = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int reside_menu_main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090016
			public const int about = 2131296278;
			
			// aapt resource value: 0x7f090019
			public const int about_msg = 2131296281;
			
			// aapt resource value: 0x7f09000b
			public const int anim_fold = 2131296267;
			
			// aapt resource value: 0x7f09000a
			public const int anim_scale = 2131296266;
			
			// aapt resource value: 0x7f09000c
			public const int anim_slide = 2131296268;
			
			// aapt resource value: 0x7f090009
			public const int anim_zoom = 2131296265;
			
			// aapt resource value: 0x7f090008
			public const int animations = 2131296264;
			
			// aapt resource value: 0x7f09001a
			public const int apache_license = 2131296282;
			
			// aapt resource value: 0x7f090000
			public const int app_name = 2131296256;
			
			// aapt resource value: 0x7f090004
			public const int attach = 2131296260;
			
			// aapt resource value: 0x7f09000d
			public const int changing_fragments = 2131296269;
			
			// aapt resource value: 0x7f090018
			public const int contact = 2131296280;
			
			// aapt resource value: 0x7f090002
			public const int general = 2131296258;
			
			// aapt resource value: 0x7f090012
			public const int github = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int github_label = 2131296275;
			
			// aapt resource value: 0x7f09000f
			public const int left = 2131296271;
			
			// aapt resource value: 0x7f090011
			public const int left_and_right = 2131296273;
			
			// aapt resource value: 0x7f090017
			public const int licenses = 2131296279;
			
			// aapt resource value: 0x7f09001b
			public const int no_email = 2131296283;
			
			// aapt resource value: 0x7f090001
			public const int properties = 2131296257;
			
			// aapt resource value: 0x7f090015
			public const int responsive_explanation = 2131296277;
			
			// aapt resource value: 0x7f09000e
			public const int responsive_ui = 2131296270;
			
			// aapt resource value: 0x7f090010
			public const int right = 2131296272;
			
			// aapt resource value: 0x7f090005
			public const int title_bar = 2131296261;
			
			// aapt resource value: 0x7f090007
			public const int title_bar_content = 2131296263;
			
			// aapt resource value: 0x7f090006
			public const int title_bar_slide = 2131296262;
			
			// aapt resource value: 0x7f090003
			public const int viewpager = 2131296259;
			
			// aapt resource value: 0x7f090014
			public const int what_is_this = 2131296276;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int DefaultTheme = 2131361792;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] reside_menu = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 3
			public const int reside_menu_behind_offset = 3;
			
			// aapt resource value: 5
			public const int reside_menu_behind_scroll_scale = 5;
			
			// aapt resource value: 4
			public const int reside_menu_behind_width = 4;
			
			// aapt resource value: 11
			public const int reside_menu_fade_degree = 11;
			
			// aapt resource value: 10
			public const int reside_menu_fade_enabled = 10;
			
			// aapt resource value: 0
			public const int reside_menu_mode = 0;
			
			// aapt resource value: 13
			public const int reside_menu_selector_drawable = 13;
			
			// aapt resource value: 12
			public const int reside_menu_selector_enabled = 12;
			
			// aapt resource value: 8
			public const int reside_menu_shadow_drawable = 8;
			
			// aapt resource value: 9
			public const int reside_menu_shadow_width = 9;
			
			// aapt resource value: 6
			public const int reside_menu_touch_mode_above = 6;
			
			// aapt resource value: 7
			public const int reside_menu_touch_mode_behind = 7;
			
			// aapt resource value: 1
			public const int reside_menu_view_above = 1;
			
			// aapt resource value: 2
			public const int reside_menu_view_behind = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
